#!/usr/bin/env bash
#Redirect to another page
apt-get -y update
apt-get -y install nginx
echo "Holberton School for the win!" | sudo tee /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me// https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
service nginx start
