#!/usr/bin/env bash
#Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School for the win!" | sudo tee /var/www/html/index.nginx-debian.html
redirect="\n\tserver_name gzoref.tech;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "42i\ $redirect" /etc/nginx/sites-available/default
sudo service nginx start
