#!/usr/bin/env bash
#Install and setup load balancer
sudo apt-get -y update
sudo apt-get install -y haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy
sudo sed -i '$ a\ \nfrontend hrrp_front\n\t bind: *80\n\tdefault_backend http_back\n\tbalance roundrobin\n\tserver 1034-web-01 35.227.27.195:80 check\n\tserver 1034-web-02 18.215.153.232:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
