#!/usr/bin/env bash
# Creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

sudo touch /var/run/holbertonscript.pid

index=0
while ((index == 0)); do
    echo "To infinity and beyond"
    sleep 2
    trap "echo I hate the kill command" SIGTERM
    trap "Y U no l" SIGINT
    trap "rm /var/run/holbertonscript.pid;exit" SIGQUIT
done
