#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 20 and:

index=1

while ((index < 10));
do
    if ((index==3));
    then
	echo "bad luck"
    elif ((index==7));
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    ((index++))
done
