#!/usr/bin/env bash
index=1
while ((index <= 20));
do
    echo $index
    case $index in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((index++))
done
